import type { TranslationDictionary } from "../types";

export const ja = {
  "locale.label": "言語", "locale.en": "English", "locale.zh-TW": "繁體中文", "locale.ja": "日本語", "locale.ko": "한국어",
  "app.menu.label": "アプリケーションメニュー", "app.menu.file": "ファイル", "app.menu.edit": "編集", "app.menu.project": "プロジェクト", "app.uiScale": "UIスケール", "app.workspaceModes": "ワークスペースモード", "app.musicEditors": "音楽エディター", "app.mode.music": "音楽", "app.mode.sfxLab": "SFXラボ", "app.mode.mixer": "ミキサー", "app.editor.song": "ソングエディター", "app.editor.pianoRoll": "ピアノロール", "app.projectDemo": "プロジェクト / SONICFORGE DEMO", "app.connecting": "接続中", "app.engineReady": "エンジン準備完了", "app.offlineMock": "オフラインモック", "app.openAudioSettings": "オーディオ設定を開く", "app.openCommandPalette": "コマンドパレットを開く", "app.tauriStatus": "Tauriステータスコマンド",
  "transport.controls": "トランスポート操作", "transport.stop": "停止", "transport.play": "再生", "transport.pause": "一時停止", "transport.record": "録音", "transport.playPause": "再生 / 一時停止",
  "browser.title": "ブラウザー", "browser.addItem": "ブラウザー項目を追加", "browser.search": "ブラウザーを検索", "browser.searchPlaceholder": "サウンドを検索", "browser.starred": "お気に入り", "browser.instruments": "楽器", "browser.drumKits": "ドラムキット", "browser.sfxRecipes": "SFXレシピ", "browser.effects": "エフェクト", "browser.samples": "サンプル", "browser.presets": "プリセット", "browser.builtinRecipes": "レシピ / 内蔵", "browser.preview": "ブラウザープレビュー", "browser.recipe.laserPulse": "レーザーパルス", "browser.recipe.deepImpact": "ディープインパクト", "browser.recipe.fastWhoosh": "ファストウーシュ", "browser.recipe.softUiClick": "ソフトUIクリック", "browser.recipe.rainAmbience": "雨のアンビエンス",
  "song.newClip": "新規クリップ", "song.newPattern": "新規パターン", "song.timeline": "ソングエディターのタイムライン", "song.bar": "小節", "song.playhead": "再生ヘッド", "song.emptyTitle": "タイムラインは空です", "song.emptyBody": "「新規クリップ」でサウンドスケッチを始めます。", "song.snap": "スナップ", "song.snap16": "1/16", "song.zoom": "ズーム", "song.timelineZoom": "タイムラインズーム", "song.clearTimeline": "タイムラインを消去", "song.clipMeta": "8小節 · seed 42",
  "piano.editor": "ピアノロールエディター", "piano.tools": "ピアノロールツール", "piano.editingTool": "編集ツール", "piano.draw": "描画", "piano.select": "選択", "piano.erase": "消去", "piano.quantize16": "1/16にクオンタイズ", "piano.duplicate": "複製", "piano.legato": "レガート", "piano.scale": "スケール", "piano.scaleLabel": "ピアノロールスケール", "piano.scale.cMajor": "Cメジャー", "piano.scale.cMinor": "Cマイナー", "piano.scale.chromatic": "クロマチック", "piano.ghostNotes": "ゴーストノート", "piano.velocity": "ベロシティ", "piano.selectedControls": "選択ノートの操作", "piano.notes": "ノート", "piano.length": "長さ", "piano.noteLength": "ノート長", "piano.noteVelocity": "ノートベロシティ", "piano.selectHint": "ノートを選択して長さやベロシティを編集", "piano.ghostsOn": "オン", "piano.ghostsOff": "オフ", "piano.toolSuffix": "ツール",
  "project.controls": "プロジェクトファイル操作", "project.saveStatus": "プロジェクト保存状態", "project.unsaved": "未保存の変更", "project.saved": "保存済み", "project.savedProjects": "保存済みプロジェクト", "project.noSavedProjects": "保存済みプロジェクトなし", "project.open": "開く", "project.save": "保存", "project.saveAs": "名前を付けて保存", "project.autosave": "自動保存", "project.autosaveInterval": "自動保存間隔", "project.minute.one": "1分", "project.minute.two": "2分", "project.minute.five": "5分", "project.minute.ten": "10分",
  "audio.engine": "リアルタイムエンジン", "audio.settings": "オーディオ設定", "audio.closeSettings": "オーディオ設定を閉じる", "audio.description": "ストリームを変更すると制御層のデバイスグラフが再起動します。オーディオコールバックではこの処理を行いません。", "audio.host": "ホスト", "audio.hostLabel": "オーディオホスト", "audio.notReported": "未報告", "audio.outputDevice": "出力デバイス", "audio.outputDeviceLabel": "オーディオ出力デバイス", "audio.default": "既定", "audio.noDevice": "デバイスの報告なし", "audio.sampleRate": "サンプルレート", "audio.sampleRateLabel": "オーディオサンプルレート", "audio.bufferSize": "バッファーサイズ", "audio.bufferSizeLabel": "オーディオバッファーサイズ", "audio.frames": "フレーム", "audio.estimatedLatency": "推定出力レイテンシー", "audio.stop": "オーディオを停止", "audio.close": "閉じる", "audio.starting": "起動中…", "audio.applyStart": "適用して起動",
  "inspector.title": "インスペクター", "inspector.recipeCode": "レシピ / 01", "inspector.trackCode": "トラック / 01", "inspector.selectClip": "クリップを選択", "inspector.selectClipHint": "トラックまたはクリップを選択してパラメーターを確認します。", "inspector.patternClip": "パターンクリップ", "inspector.clipTransform": "クリップ変形", "inspector.position": "位置", "inspector.length": "長さ", "inspector.clipLength": "クリップ長", "inspector.color": "色", "inspector.actions": "操作", "inspector.duplicate": "複製", "inspector.split": "再生ヘッドで分割", "inspector.freezeAudio": "オーディオをフリーズ", "inspector.commandBoundary": "UI編集はプロジェクトコマンド層に留まり、DSPノードはRust側に残ります。",
  "sfx.recipeBuiltin": "レシピ / 内蔵 / 01", "sfx.laserPulse": "レーザーパルス", "sfx.laserDescription": "明るいアタックと短いテールを持つ下降スイープ。", "sfx.waveform": "レーザー波形", "sfx.preview": "プレビュー", "sfx.freezeTrack": "トラックにフリーズ", "sfx.macros": "マクロ", "sfx.lockedHint": "ロックした値は固定されます", "sfx.macro.character": "キャラクター", "sfx.macro.pitch": "ピッチ", "sfx.macro.body": "ボディ", "sfx.macro.noise": "ノイズ", "sfx.macro.space": "空間", "sfx.macro.length": "長さ", "sfx.deterministicHint": "決定論的プレビュー。同じseedとパラメーターは常に同じPCMを生成します。", "sfx.advancedParameters": "詳細パラメーター", "sfx.renderControl": "レンダー制御", "sfx.recipeVersion": "レーザー / V1", "sfx.seed": "Seed", "sfx.seedLabel": "SFX seed", "sfx.unlockSeed": "seedのロック解除", "sfx.lockSeed": "seedをロック", "sfx.variants": "バリエーション", "sfx.variantCount": "バリエーション数", "sfx.variant.one": "1バリエーション", "sfx.variant.eight": "8バリエーション", "sfx.variant.sixteen": "16バリエーション", "sfx.variant.thirtyTwo": "32バリエーション", "sfx.peakTarget": "ピーク目標", "sfx.randomize": "ランダム化", "sfx.exportBatch": "一括エクスポート",
  "mixer.eventFlow": "ミキサー / イベントフロー", "mixer.title": "ミキサー", "mixer.automation": "オートメーション", "mixer.eventList": "イベントリスト", "mixer.master": "マスター", "mixer.liveView": "ミックスバス / ライブビュー", "mixer.headline": "ミックスの輪郭をコントロール。", "mixer.description": "Rust制御キューが接続されるまで、ゲインとミュートはローカルUI状態です。", "mixer.mute": "ミュート", "mixer.unmute": "ミュート解除", "mixer.gain": "ゲイン", "mixer.muted": "ミュート中",
  "command.palette": "コマンドパレット", "command.search": "コマンド検索", "command.placeholder": "コマンドを入力", "command.openSongEditor": "ソングエディターを開く", "command.openSfxLab": "SFXラボを開く", "command.openMixer": "ミキサーを開く", "command.escapeClose": "ESCで閉じる", "command.controlLayer": "コマンドは制御層を通じて実行されます",
  "template.browserSelected": "{item}ブラウザーを選択しました", "template.recipeLoaded": "{recipe}をSFXラボに読み込みました", "template.selectClip": "{name}を選択", "template.timelineZoom": "タイムラインズーム {percent}%", "template.pianoCanvas": "{count}個のノート。{selection}。描画、選択、消去ツールを使用できます。", "template.noteSelected": "{note}を選択中", "template.noNoteSelected": "ノート未選択", "template.noteCount": "{count} ノート", "template.pianoState": "{scale} · ゴースト{ghosts} · {tool}ツール", "template.autosaved": "{name}を自動保存しました", "template.loaded": "{name}を読み込みました", "template.saved": "{fileName}を保存しました", "template.savedAs": "{fileName}として保存しました", "template.autosaveEvery": "{minutes}分ごとに自動保存", "template.deviceOption": "{name} · {channels}ch{defaultSuffix}", "template.audioSummary": "{sampleRate} Hz · {bufferSize}フレーム · {state}", "template.mixerAction": "{name}を{action}",
  "status.ready": "新しいサウンドの準備完了", "status.browserReady": "新しいコレクションを作成できます", "status.newClip": "選択トラックに新規クリップを追加しました", "status.clipDuplicated": "クリップを複製しました", "status.clipSplit": "再生ヘッドでクリップを分割しました", "status.clipMoved": "グリッド上でクリップを移動しました", "status.timelineCleared": "タイムラインを消去しました — クリップを追加してください", "status.seedLocked": "Seedはロック中です — ランダム化の前に解除してください", "status.newSeed": "新しい決定論的seedを生成しました", "status.transportPaused": "再生を一時停止しました", "status.transportPlaying": "再生中", "status.transportStopped": "再生を停止しました", "status.snap16": "スナップを1/16に設定", "status.automationReady": "オートメーションレーンは次のエンジンスライスに対応できます", "status.eventListEmpty": "プレビューのイベントリストは空です", "status.masterMutePreview": "マスターミュートはプレビュー専用です", "status.masterGainPreview": "マスターゲインはプレビュー専用です", "status.previewingLaser": "レーザーパルスをプレビュー中", "status.advancedExpanded": "詳細パラメーターを展開しました", "status.batchQueued": "一括エクスポートをレンダーワーカーに追加しました", "status.freezeReady": "非破壊フリーズの準備ができました", "status.autosaveDisabled": "自動保存を無効にしました", "status.autosaveFailed": "自動保存に失敗しました", "status.projectCommandFailed": "プロジェクトコマンドに失敗しました", "status.audioLoadFailed": "オーディオ設定を読み込めませんでした", "status.audioStarted": "オーディオデバイスを起動しました", "status.audioUnavailable": "オーディオデバイスを利用できません", "status.audioConfigFailed": "オーディオ設定に失敗しました", "status.audioStopped": "オーディオデバイスを停止しました", "status.audioStopFailed": "オーディオデバイスを停止できませんでした", "status.noteErased": "ノートを消去しました", "status.noteDrawn": "ノートを描画しました", "status.noteQuantized": "選択ノートを1/16にクオンタイズしました", "status.noteDuplicated": "ノートを複製しました", "status.noteLegato": "次のノートまでレガートを延長しました", "status.selectedNoteErased": "選択ノートを消去しました", "status.noteResized": "ノート長を変更しました", "status.noteVelocityChanged": "ノートベロシティを変更しました",
  "templates.open": "テンプレート", "templates.title": "テンプレートから開始", "templates.description": "完全なプロジェクトモデルを読み込み、編集または別名で保存できます。", "templates.close": "テンプレートを閉じる", "templates.use": "このテンプレートを使用", "templates.blank.title": "空のプロジェクト", "templates.blank.description": "最初のトラックを追加できる120 BPMの空プロジェクト。", "templates.twinkle.title": "きらきら星", "templates.twinkle.description": "編集可能な48拍ピアノパターンにしたパブリックドメイン曲。", "templates.fourBeatDrums.title": "4ビートドラム", "templates.fourBeatDrums.description": "ループ可能なキック、スネア、ハイハットの基本グルーヴ。", "templates.chiptune.title": "チップチューンループ", "templates.chiptune.description": "8拍ゲームループ向けのパルスリードとベース。", "templates.sfxStarter.title": "SFXスターター", "templates.sfxStarter.description": "決定論的レーザーレシピとトリガートラック。", "status.templateLoaded": "テンプレートを読み込みました — 変更を保存してください",
  "templates.category.starter": "スターター", "templates.category.music": "音楽", "templates.category.rhythm": "リズム", "templates.category.electronic": "電子音楽", "templates.category.sfx": "効果音",
  "app.editor.stepSequencer": "ステップシーケンサー",
  "sequencer.title": "ステップシーケンサー", "sequencer.steps": "{count}/64 ステップ", "sequencer.play": "パターンを再生", "sequencer.pause": "パターンを一時停止", "sequencer.undo": "元に戻す", "sequencer.redo": "やり直す", "sequencer.patternLength": "パターン長", "sequencer.stepsUnit": "ステップ", "sequencer.swing": "スウィング", "sequencer.keyboardHint": "キーボード：矢印で移動 · Spaceで切替", "sequencer.grid": "ステップグリッド", "sequencer.step": "ステップ {number}", "sequencer.active": "有効", "sequencer.inactive": "無効", "sequencer.selectedControls": "選択ステップの操作", "sequencer.on": "オン", "sequencer.off": "オフ", "sequencer.probability": "確率", "sequencer.microShift": "マイクロシフト", "sequencer.ratchet": "ラチェット", "sequencer.footer": "ベロシティ · 確率 · マイクロシフト · ラチェット", "sequencer.history": "最大200操作の履歴", "status.stepChanged": "ステップパターンを変更しました", "status.recovered": "未保存のプロジェクトスナップショットを復元しました",
} satisfies TranslationDictionary;
