import type { TranslationDictionary } from "../types";

export const ko = {
  "locale.label": "언어", "locale.en": "English", "locale.zh-TW": "繁體中文", "locale.ja": "日本語", "locale.ko": "한국어",
  "app.menu.label": "애플리케이션 메뉴", "app.menu.file": "파일", "app.menu.edit": "편집", "app.menu.project": "프로젝트", "app.uiScale": "UI 배율", "app.workspaceModes": "작업 공간 모드", "app.musicEditors": "음악 편집기", "app.mode.music": "음악", "app.mode.sfxLab": "SFX 랩", "app.mode.mixer": "믹서", "app.editor.song": "송 에디터", "app.editor.pianoRoll": "피아노 롤", "app.projectDemo": "프로젝트 / SONICFORGE DEMO", "app.connecting": "연결 중", "app.engineReady": "엔진 준비됨", "app.offlineMock": "오프라인 모의", "app.openAudioSettings": "오디오 설정 열기", "app.openCommandPalette": "명령 팔레트 열기", "app.tauriStatus": "Tauri 상태 명령",
  "transport.controls": "트랜스포트 컨트롤", "transport.stop": "정지", "transport.play": "재생", "transport.pause": "일시 정지", "transport.record": "녹음", "transport.playPause": "재생 / 일시 정지",
  "browser.title": "브라우저", "browser.addItem": "브라우저 항목 추가", "browser.search": "브라우저 검색", "browser.searchPlaceholder": "사운드 검색", "browser.starred": "즐겨찾기", "browser.instruments": "악기", "browser.drumKits": "드럼 키트", "browser.sfxRecipes": "SFX 레시피", "browser.effects": "이펙트", "browser.samples": "샘플", "browser.presets": "프리셋", "browser.builtinRecipes": "레시피 / 내장", "browser.preview": "브라우저 미리보기", "browser.recipe.laserPulse": "레이저 펄스", "browser.recipe.deepImpact": "딥 임팩트", "browser.recipe.fastWhoosh": "빠른 우시", "browser.recipe.softUiClick": "부드러운 UI 클릭", "browser.recipe.rainAmbience": "빗소리 앰비언스",
  "song.newClip": "새 클립", "song.newPattern": "새 패턴", "song.timeline": "송 에디터 타임라인", "song.bar": "마디", "song.playhead": "재생 헤드", "song.emptyTitle": "타임라인이 비어 있습니다", "song.emptyBody": "‘새 클립’을 사용해 사운드 스케치를 시작하세요.", "song.snap": "스냅", "song.snap16": "1/16", "song.zoom": "확대/축소", "song.timelineZoom": "타임라인 배율", "song.clearTimeline": "타임라인 지우기", "song.clipMeta": "8마디 · seed 42",
  "piano.editor": "피아노 롤 편집기", "piano.tools": "피아노 롤 도구", "piano.editingTool": "편집 도구", "piano.draw": "그리기", "piano.select": "선택", "piano.erase": "지우기", "piano.quantize16": "1/16 퀀타이즈", "piano.duplicate": "복제", "piano.legato": "레가토", "piano.scale": "스케일", "piano.scaleLabel": "피아노 롤 스케일", "piano.scale.cMajor": "C 장조", "piano.scale.cMinor": "C 단조", "piano.scale.chromatic": "크로매틱", "piano.ghostNotes": "고스트 노트", "piano.velocity": "벨로시티", "piano.selectedControls": "선택한 노트 컨트롤", "piano.notes": "노트", "piano.length": "길이", "piano.noteLength": "노트 길이", "piano.noteVelocity": "노트 벨로시티", "piano.selectHint": "길이 또는 벨로시티를 편집할 노트를 선택하세요", "piano.ghostsOn": "켜짐", "piano.ghostsOff": "꺼짐", "piano.toolSuffix": "도구",
  "project.controls": "프로젝트 파일 컨트롤", "project.saveStatus": "프로젝트 저장 상태", "project.unsaved": "저장되지 않은 변경 사항", "project.saved": "저장됨", "project.savedProjects": "저장된 프로젝트", "project.noSavedProjects": "저장된 프로젝트 없음", "project.open": "열기", "project.save": "저장", "project.saveAs": "다른 이름으로 저장", "project.autosave": "자동 저장", "project.autosaveInterval": "자동 저장 간격", "project.minute.one": "1분", "project.minute.two": "2분", "project.minute.five": "5분", "project.minute.ten": "10분",
  "audio.engine": "실시간 엔진", "audio.settings": "오디오 설정", "audio.closeSettings": "오디오 설정 닫기", "audio.description": "스트림을 변경하면 제어 계층의 장치 그래프가 다시 시작됩니다. 오디오 콜백은 이 작업을 수행하지 않습니다.", "audio.host": "호스트", "audio.hostLabel": "오디오 호스트", "audio.notReported": "보고되지 않음", "audio.outputDevice": "출력 장치", "audio.outputDeviceLabel": "오디오 출력 장치", "audio.default": "기본값", "audio.noDevice": "보고된 장치 없음", "audio.sampleRate": "샘플 레이트", "audio.sampleRateLabel": "오디오 샘플 레이트", "audio.bufferSize": "버퍼 크기", "audio.bufferSizeLabel": "오디오 버퍼 크기", "audio.frames": "프레임", "audio.estimatedLatency": "예상 출력 지연", "audio.stop": "오디오 중지", "audio.close": "닫기", "audio.starting": "시작 중…", "audio.applyStart": "적용 및 시작",
  "inspector.title": "인스펙터", "inspector.recipeCode": "레시피 / 01", "inspector.trackCode": "트랙 / 01", "inspector.selectClip": "클립 선택", "inspector.selectClipHint": "파라미터를 확인할 트랙 또는 클립을 선택하세요.", "inspector.patternClip": "패턴 클립", "inspector.clipTransform": "클립 변형", "inspector.position": "위치", "inspector.length": "길이", "inspector.clipLength": "클립 길이", "inspector.color": "색상", "inspector.actions": "작업", "inspector.duplicate": "복제", "inspector.split": "재생 헤드에서 분할", "inspector.freezeAudio": "오디오 프리즈", "inspector.commandBoundary": "UI 편집은 프로젝트 명령 계층에 유지되고 DSP 노드는 Rust 측에 남습니다.",
  "sfx.recipeBuiltin": "레시피 / 내장 / 01", "sfx.laserPulse": "레이저 펄스", "sfx.laserDescription": "밝은 트랜지언트와 짧은 테일이 있는 하강 스윕입니다.", "sfx.waveform": "레이저 파형", "sfx.preview": "미리 듣기", "sfx.freezeTrack": "트랙에 프리즈", "sfx.macros": "매크로", "sfx.lockedHint": "잠긴 값은 고정됩니다", "sfx.macro.character": "캐릭터", "sfx.macro.pitch": "피치", "sfx.macro.body": "바디", "sfx.macro.noise": "노이즈", "sfx.macro.space": "공간", "sfx.macro.length": "길이", "sfx.deterministicHint": "결정적 미리 듣기. 같은 seed와 파라미터는 항상 동일한 PCM을 렌더링합니다.", "sfx.advancedParameters": "고급 파라미터", "sfx.renderControl": "렌더 제어", "sfx.recipeVersion": "레이저 / V1", "sfx.seed": "Seed", "sfx.seedLabel": "SFX seed", "sfx.unlockSeed": "seed 잠금 해제", "sfx.lockSeed": "seed 잠금", "sfx.variants": "변형", "sfx.variantCount": "변형 수", "sfx.variant.one": "변형 1개", "sfx.variant.eight": "변형 8개", "sfx.variant.sixteen": "변형 16개", "sfx.variant.thirtyTwo": "변형 32개", "sfx.peakTarget": "피크 목표", "sfx.randomize": "무작위화", "sfx.exportBatch": "일괄 내보내기",
  "mixer.eventFlow": "믹서 / 이벤트 흐름", "mixer.title": "믹서", "mixer.automation": "오토메이션", "mixer.eventList": "이벤트 목록", "mixer.master": "마스터", "mixer.liveView": "믹스 버스 / 라이브 보기", "mixer.headline": "믹스의 형태를 제어하세요.", "mixer.description": "Rust 제어 큐가 연결되기 전까지 게인과 음소거는 로컬 UI 상태입니다.", "mixer.mute": "음소거", "mixer.unmute": "음소거 해제", "mixer.gain": "게인", "mixer.muted": "음소거됨",
  "command.palette": "명령 팔레트", "command.search": "명령 검색", "command.placeholder": "명령 입력", "command.openSongEditor": "송 에디터 열기", "command.openSfxLab": "SFX 랩 열기", "command.openMixer": "믹서 열기", "command.escapeClose": "ESC로 닫기", "command.controlLayer": "명령은 제어 계층을 통해 실행됩니다",
  "template.browserSelected": "{item} 브라우저를 선택했습니다", "template.recipeLoaded": "{recipe}을(를) SFX 랩에 불러왔습니다", "template.selectClip": "{name} 선택", "template.timelineZoom": "타임라인 배율 {percent}%", "template.pianoCanvas": "노트 {count}개. {selection}. 그리기, 선택 또는 지우기 도구를 사용하세요.", "template.noteSelected": "{note} 선택됨", "template.noNoteSelected": "선택된 노트 없음", "template.noteCount": "노트 {count}개", "template.pianoState": "{scale} · 고스트 {ghosts} · {tool} 도구", "template.autosaved": "{name} 자동 저장됨", "template.loaded": "{name} 불러옴", "template.saved": "{fileName} 저장됨", "template.savedAs": "{fileName}(으)로 저장됨", "template.autosaveEvery": "{minutes}분마다 자동 저장", "template.deviceOption": "{name} · {channels}ch{defaultSuffix}", "template.audioSummary": "{sampleRate} Hz · {bufferSize}프레임 · {state}", "template.mixerAction": "{name} {action}",
  "status.ready": "새 사운드를 만들 준비가 되었습니다", "status.browserReady": "새 컬렉션을 만들 준비가 되었습니다", "status.newClip": "선택한 트랙에 새 클립을 추가했습니다", "status.clipDuplicated": "클립을 복제했습니다", "status.clipSplit": "재생 헤드에서 클립을 분할했습니다", "status.clipMoved": "그리드에서 클립을 이동했습니다", "status.timelineCleared": "타임라인을 지웠습니다 — 클립을 추가하세요", "status.seedLocked": "Seed가 잠겨 있습니다 — 무작위화 전에 잠금을 해제하세요", "status.newSeed": "새 결정적 seed를 생성했습니다", "status.transportPaused": "재생이 일시 정지되었습니다", "status.transportPlaying": "재생 중", "status.transportStopped": "재생이 중지되었습니다", "status.snap16": "스냅을 1/16로 설정했습니다", "status.automationReady": "오토메이션 레인이 다음 엔진 슬라이스를 위해 준비되었습니다", "status.eventListEmpty": "미리보기 이벤트 목록이 비어 있습니다", "status.masterMutePreview": "마스터 음소거는 미리보기 전용입니다", "status.masterGainPreview": "마스터 게인은 미리보기 전용입니다", "status.previewingLaser": "레이저 펄스 미리 듣는 중", "status.advancedExpanded": "고급 파라미터를 펼쳤습니다", "status.batchQueued": "일괄 내보내기를 렌더 워커에 추가했습니다", "status.freezeReady": "비파괴 프리즈 준비가 되었습니다", "status.autosaveDisabled": "자동 저장을 비활성화했습니다", "status.autosaveFailed": "자동 저장 실패", "status.projectCommandFailed": "프로젝트 명령 실패", "status.audioLoadFailed": "오디오 설정을 불러올 수 없습니다", "status.audioStarted": "오디오 장치를 시작했습니다", "status.audioUnavailable": "오디오 장치를 사용할 수 없습니다", "status.audioConfigFailed": "오디오 구성 실패", "status.audioStopped": "오디오 장치를 중지했습니다", "status.audioStopFailed": "오디오 장치를 중지할 수 없습니다", "status.noteErased": "노트를 지웠습니다", "status.noteDrawn": "노트를 그렸습니다", "status.noteQuantized": "선택한 노트를 1/16로 퀀타이즈했습니다", "status.noteDuplicated": "노트를 복제했습니다", "status.noteLegato": "다음 노트까지 레가토를 연장했습니다", "status.selectedNoteErased": "선택한 노트를 지웠습니다", "status.noteResized": "노트 길이를 변경했습니다", "status.noteVelocityChanged": "노트 벨로시티를 변경했습니다",
  "templates.open": "템플릿", "templates.title": "템플릿으로 시작", "templates.description": "완전한 프로젝트 모델을 불러온 뒤 편집하거나 새 이름으로 저장하세요.", "templates.close": "템플릿 닫기", "templates.use": "템플릿 사용", "templates.blank.title": "빈 프로젝트", "templates.blank.description": "첫 트랙을 추가할 수 있는 120 BPM 빈 프로젝트입니다.", "templates.twinkle.title": "작은 별", "templates.twinkle.description": "편집 가능한 48박 피아노 패턴으로 구성한 퍼블릭 도메인 곡입니다.", "templates.fourBeatDrums.title": "4비트 드럼", "templates.fourBeatDrums.description": "반복 가능한 킥, 스네어, 하이햇 기본 그루브입니다.", "templates.chiptune.title": "칩튠 루프", "templates.chiptune.description": "8박 게임 루프용 펄스 리드와 베이스 패턴입니다.", "templates.sfxStarter.title": "SFX 스타터", "templates.sfxStarter.description": "결정적 레이저 레시피와 트리거 트랙입니다.", "status.templateLoaded": "템플릿을 불러왔습니다 — 변경 사항을 저장하세요",
  "templates.category.starter": "시작", "templates.category.music": "음악", "templates.category.rhythm": "리듬", "templates.category.electronic": "전자 음악", "templates.category.sfx": "효과음",
  "app.editor.stepSequencer": "스텝 시퀀서",
  "sequencer.title": "스텝 시퀀서", "sequencer.steps": "{count}/64 스텝", "sequencer.play": "패턴 재생", "sequencer.pause": "패턴 일시 정지", "sequencer.undo": "실행 취소", "sequencer.redo": "다시 실행", "sequencer.patternLength": "패턴 길이", "sequencer.stepsUnit": "스텝", "sequencer.swing": "스윙", "sequencer.keyboardHint": "키보드: 화살표 이동 · Space 전환", "sequencer.grid": "스텝 그리드", "sequencer.step": "스텝 {number}", "sequencer.active": "활성", "sequencer.inactive": "비활성", "sequencer.selectedControls": "선택한 스텝 컨트롤", "sequencer.on": "켜짐", "sequencer.off": "꺼짐", "sequencer.probability": "확률", "sequencer.microShift": "마이크로 시프트", "sequencer.ratchet": "래칫", "sequencer.footer": "벨로시티 · 확률 · 마이크로 시프트 · 래칫", "sequencer.history": "최대 200개 작업 기록", "status.stepChanged": "스텝 패턴이 변경되었습니다", "status.recovered": "저장되지 않은 프로젝트 스냅샷을 복구했습니다",
} satisfies TranslationDictionary;
