import type { TranslationDictionary } from "../types";

export const zhTW = {
  "locale.label": "語言", "locale.en": "English", "locale.zh-TW": "繁體中文", "locale.ja": "日本語", "locale.ko": "한국어",
  "app.menu.label": "應用程式選單", "app.menu.file": "檔案", "app.menu.edit": "編輯", "app.menu.project": "專案", "app.uiScale": "介面縮放", "app.workspaceModes": "工作區模式", "app.musicEditors": "音樂編輯器", "app.mode.music": "音樂", "app.mode.sfxLab": "音效實驗室", "app.mode.mixer": "混音器", "app.editor.song": "歌曲編輯器", "app.editor.pianoRoll": "鋼琴捲簾", "app.projectDemo": "專案 / SONICFORGE DEMO", "app.connecting": "連線中", "app.engineReady": "引擎已就緒", "app.offlineMock": "離線模擬", "app.openAudioSettings": "開啟音訊設定", "app.openCommandPalette": "開啟命令面板", "app.tauriStatus": "Tauri 狀態命令",
  "transport.controls": "播放控制", "transport.stop": "停止", "transport.play": "播放", "transport.pause": "暫停", "transport.record": "錄音", "transport.playPause": "播放 / 暫停",
  "browser.title": "瀏覽器", "browser.addItem": "新增瀏覽項目", "browser.search": "搜尋瀏覽器", "browser.searchPlaceholder": "搜尋聲音", "browser.starred": "已加星號", "browser.instruments": "樂器", "browser.drumKits": "鼓組", "browser.sfxRecipes": "音效配方", "browser.effects": "效果器", "browser.samples": "取樣", "browser.presets": "預設集", "browser.builtinRecipes": "配方 / 內建", "browser.preview": "瀏覽器預覽", "browser.recipe.laserPulse": "雷射脈衝", "browser.recipe.deepImpact": "深沉撞擊", "browser.recipe.fastWhoosh": "快速掠聲", "browser.recipe.softUiClick": "柔和介面點擊", "browser.recipe.rainAmbience": "雨聲氛圍",
  "song.newClip": "新增片段", "song.newPattern": "新 Pattern", "song.timeline": "歌曲編輯器時間軸", "song.bar": "小節", "song.playhead": "播放頭", "song.emptyTitle": "時間軸是空的", "song.emptyBody": "使用「新增片段」開始聲音草稿。", "song.snap": "吸附", "song.snap16": "1/16", "song.zoom": "縮放", "song.timelineZoom": "時間軸縮放", "song.clearTimeline": "清空時間軸", "song.clipMeta": "8 小節 · seed 42",
  "piano.editor": "鋼琴捲簾編輯器", "piano.tools": "鋼琴捲簾工具", "piano.editingTool": "編輯工具", "piano.draw": "繪製", "piano.select": "選取", "piano.erase": "擦除", "piano.quantize16": "量化至 1/16", "piano.duplicate": "複製", "piano.legato": "圓滑奏", "piano.scale": "音階", "piano.scaleLabel": "鋼琴捲簾音階", "piano.scale.cMajor": "C 大調", "piano.scale.cMinor": "C 小調", "piano.scale.chromatic": "半音階", "piano.ghostNotes": "幽靈音符", "piano.velocity": "力度", "piano.selectedControls": "選取音符控制", "piano.notes": "音符", "piano.length": "長度", "piano.noteLength": "音符長度", "piano.noteVelocity": "音符力度", "piano.selectHint": "選取音符以調整長度或力度", "piano.ghostsOn": "開", "piano.ghostsOff": "關", "piano.toolSuffix": "工具",
  "project.controls": "專案檔案控制", "project.saveStatus": "專案儲存狀態", "project.unsaved": "有未儲存變更", "project.saved": "已儲存", "project.savedProjects": "已儲存專案", "project.noSavedProjects": "沒有已儲存專案", "project.open": "開啟", "project.save": "儲存", "project.saveAs": "另存新檔", "project.autosave": "自動儲存", "project.autosaveInterval": "自動儲存間隔", "project.minute.one": "1 分鐘", "project.minute.two": "2 分鐘", "project.minute.five": "5 分鐘", "project.minute.ten": "10 分鐘",
  "audio.engine": "即時引擎", "audio.settings": "音訊設定", "audio.closeSettings": "關閉音訊設定", "audio.description": "變更串流會重新啟動控制層裝置圖；音訊 callback 絕不執行這項工作。", "audio.host": "主機", "audio.hostLabel": "音訊主機", "audio.notReported": "未回報", "audio.outputDevice": "輸出裝置", "audio.outputDeviceLabel": "音訊輸出裝置", "audio.default": "預設", "audio.noDevice": "未回報裝置", "audio.sampleRate": "取樣率", "audio.sampleRateLabel": "音訊取樣率", "audio.bufferSize": "緩衝區大小", "audio.bufferSizeLabel": "音訊緩衝區大小", "audio.frames": "frames", "audio.estimatedLatency": "預估輸出延遲", "audio.stop": "停止音訊", "audio.close": "關閉", "audio.starting": "啟動中…", "audio.applyStart": "套用並啟動",
  "inspector.title": "檢查器", "inspector.recipeCode": "配方 / 01", "inspector.trackCode": "軌道 / 01", "inspector.selectClip": "選取片段", "inspector.selectClipHint": "選擇軌道或片段以檢查參數。", "inspector.patternClip": "Pattern 片段", "inspector.clipTransform": "片段變形", "inspector.position": "位置", "inspector.length": "長度", "inspector.clipLength": "片段長度", "inspector.color": "顏色", "inspector.actions": "操作", "inspector.duplicate": "複製", "inspector.split": "在播放頭分割", "inspector.freezeAudio": "凍結音訊", "inspector.commandBoundary": "介面編輯留在專案命令層；DSP 節點仍位於 Rust 端。",
  "sfx.recipeBuiltin": "配方 / 內建 / 01", "sfx.laserPulse": "雷射脈衝", "sfx.laserDescription": "帶明亮起音與緊湊尾音的向下掃頻。", "sfx.waveform": "雷射波形", "sfx.preview": "預聽", "sfx.freezeTrack": "凍結至軌道", "sfx.macros": "巨集", "sfx.lockedHint": "已鎖定數值保持固定", "sfx.macro.character": "音色", "sfx.macro.pitch": "音高", "sfx.macro.body": "厚度", "sfx.macro.noise": "噪聲", "sfx.macro.space": "空間", "sfx.macro.length": "長度", "sfx.deterministicHint": "確定性預聽：相同 seed 與參數永遠產生相同 PCM。", "sfx.advancedParameters": "進階參數", "sfx.renderControl": "渲染控制", "sfx.recipeVersion": "雷射 / V1", "sfx.seed": "Seed", "sfx.seedLabel": "音效 seed", "sfx.unlockSeed": "解除 seed 鎖定", "sfx.lockSeed": "鎖定 seed", "sfx.variants": "變體", "sfx.variantCount": "變體數量", "sfx.variant.one": "1 個變體", "sfx.variant.eight": "8 個變體", "sfx.variant.sixteen": "16 個變體", "sfx.variant.thirtyTwo": "32 個變體", "sfx.peakTarget": "峰值目標", "sfx.randomize": "隨機化", "sfx.exportBatch": "批次匯出",
  "mixer.eventFlow": "混音器 / 事件流", "mixer.title": "混音器", "mixer.automation": "自動化", "mixer.eventList": "事件清單", "mixer.master": "主控", "mixer.liveView": "混音匯流排 / 即時檢視", "mixer.headline": "掌控混音的輪廓。", "mixer.description": "在 Rust 控制佇列接通前，增益與靜音僅是本機介面狀態。", "mixer.mute": "靜音", "mixer.unmute": "取消靜音", "mixer.gain": "增益", "mixer.muted": "已靜音",
  "command.palette": "命令面板", "command.search": "命令搜尋", "command.placeholder": "輸入命令", "command.openSongEditor": "開啟歌曲編輯器", "command.openSfxLab": "開啟音效實驗室", "command.openMixer": "開啟混音器", "command.escapeClose": "按 ESC 關閉", "command.controlLayer": "命令透過控制層執行",
  "template.browserSelected": "已選取 {item} 瀏覽器", "template.recipeLoaded": "已將 {recipe} 載入音效實驗室", "template.selectClip": "選取 {name}", "template.timelineZoom": "時間軸縮放 {percent}%", "template.pianoCanvas": "{count} 個音符。{selection}。使用繪製、選取或擦除工具。", "template.noteSelected": "已選取 {note}", "template.noNoteSelected": "未選取音符", "template.noteCount": "{count} 個音符", "template.pianoState": "{scale} · 幽靈音符{ghosts} · {tool}工具", "template.autosaved": "已自動儲存 {name}", "template.loaded": "已載入 {name}", "template.saved": "已儲存 {fileName}", "template.savedAs": "已另存為 {fileName}", "template.autosaveEvery": "每 {minutes} 分鐘自動儲存", "template.deviceOption": "{name} · {channels}ch{defaultSuffix}", "template.audioSummary": "{sampleRate} Hz · {bufferSize} frames · {state}", "template.mixerAction": "{action} {name}",
  "status.ready": "已準備好建立新聲音", "status.browserReady": "瀏覽器已準備好建立新集合", "status.newClip": "已將新片段加入選取軌道", "status.clipDuplicated": "已複製片段", "status.clipSplit": "已在播放頭分割片段", "status.clipMoved": "已在格線上移動片段", "status.timelineCleared": "已清空時間軸 — 新增片段即可開始", "status.seedLocked": "Seed 已鎖定 — 請先解除鎖定再隨機化", "status.newSeed": "已產生新的確定性 seed", "status.transportPaused": "播放已暫停", "status.transportPlaying": "正在播放", "status.transportStopped": "播放已停止", "status.snap16": "吸附設為 1/16", "status.automationReady": "自動化軌已準備給下一個引擎切片", "status.eventListEmpty": "預覽中的事件清單是空的", "status.masterMutePreview": "主控靜音僅供預覽", "status.masterGainPreview": "主控增益僅供預覽", "status.previewingLaser": "正在預聽雷射脈衝", "status.advancedExpanded": "已展開進階參數", "status.batchQueued": "批次匯出已加入渲染 worker 佇列", "status.freezeReady": "片段已可進行非破壞性凍結", "status.autosaveDisabled": "已停用自動儲存", "status.autosaveFailed": "自動儲存失敗", "status.projectCommandFailed": "專案命令失敗", "status.audioLoadFailed": "無法載入音訊設定", "status.audioStarted": "音訊裝置已啟動", "status.audioUnavailable": "音訊裝置無法使用", "status.audioConfigFailed": "音訊設定失敗", "status.audioStopped": "音訊裝置已停止", "status.audioStopFailed": "無法停止音訊裝置", "status.noteErased": "已擦除音符", "status.noteDrawn": "已繪製音符", "status.noteQuantized": "已將選取音符量化至 1/16", "status.noteDuplicated": "已複製音符", "status.noteLegato": "圓滑奏已延伸至下一音符", "status.selectedNoteErased": "已擦除選取音符", "status.noteResized": "已調整音符長度", "status.noteVelocityChanged": "已變更音符力度",
  "templates.open": "範本", "templates.title": "從範本開始", "templates.description": "載入完整專案模型後，可直接編輯或另存成自己的作品。", "templates.close": "關閉範本", "templates.use": "使用範本", "templates.blank.title": "空白專案", "templates.blank.description": "120 BPM 空白專案，可立即加入第一條軌道。", "templates.twinkle.title": "小星星", "templates.twinkle.description": "以可編輯 48 拍鋼琴 pattern 編排的公版旋律。", "templates.fourBeatDrums.title": "四拍鼓組", "templates.fourBeatDrums.description": "可循環的底鼓、軍鼓與 hi-hat 起始節奏。", "templates.chiptune.title": "晶片音樂循環", "templates.chiptune.description": "適合八拍遊戲循環的方波主奏與低音。", "templates.sfxStarter.title": "音效起始範本", "templates.sfxStarter.description": "確定性雷射配方與觸發軌道。", "status.templateLoaded": "已載入範本 — 請儲存以保留變更",
  "templates.category.starter": "入門", "templates.category.music": "音樂", "templates.category.rhythm": "節奏", "templates.category.electronic": "電子音樂", "templates.category.sfx": "音效",
  "app.editor.stepSequencer": "步進音序器",
  "sequencer.title": "步進音序器", "sequencer.steps": "{count}/64 步", "sequencer.play": "播放節奏", "sequencer.pause": "暫停節奏", "sequencer.undo": "復原", "sequencer.redo": "重做", "sequencer.patternLength": "Pattern 長度", "sequencer.stepsUnit": "步", "sequencer.swing": "Swing", "sequencer.keyboardHint": "鍵盤：方向鍵移動 · 空白鍵切換", "sequencer.grid": "步進網格", "sequencer.step": "第 {number} 步", "sequencer.active": "啟用", "sequencer.inactive": "停用", "sequencer.selectedControls": "選取步驟控制", "sequencer.on": "開", "sequencer.off": "關", "sequencer.probability": "機率", "sequencer.microShift": "微移位", "sequencer.ratchet": "重複觸發", "sequencer.footer": "力度 · 機率 · 微移位 · 重複觸發", "sequencer.history": "最多 200 次歷史操作", "status.stepChanged": "步進 Pattern 已變更", "status.recovered": "已復原上次未儲存的專案快照",
} satisfies TranslationDictionary;
